### ISSUE TITLE
Hillshade uses incorrect resolution when determining slope angles

### ISSUE THREAD

**Issue by mike-000** [openlayers/ol-mapbox-style#883] opened 2023-04-08 18:22 UTC
The resolution in projection units is used to calculate slopes, while DEM sources provide elevations in true meters.  Therefore if Kilimanjaro was moved to Norway is would appear to be only half as steep.  Mapbox appears to compensate for that (as it does when extruding buildings).  When using `ol/source/Raster` I think the best that could be provided would be the point resolution of the view center in true meters (adjusted for pixel ratio) which could be included in the `beforeoperations` RasterSourceEvent (or it could simply include the entire `frameState` and leave the detail to the application).  A WebGL implementation could potentially make an adjustment specific to each tile.

**Comment by ahocevar** [comment] 2023-04-08 20:45
Is this really something that makes a noticeable difference? Can you provide a reference to the mapbox-gl-js code that performes the mentioned compensation?

If so, then why so complicated? We currently pass the `beforeoperations` event's `resolution` to the Raster source data. Instead, we could simply pass the point resolution at the extent's center. The `extent` is available as `beforeoperations` event property too. And since we're using tile pixels and not css pixels, we don't need to mess with pixel ratio.

**Comment by mike-000** [comment] 2023-04-08 22:35
This appears to be the code used
 in Mapbox https://github.com/mapbox/mapbox-gl-js/blob/main/src/render/program/hillshade_program.js#L106
 and Maplibre https://github.com/maplibre/maplibre-gl-js/blob/main/src/render/program/hillshade_program.ts

The event `resolution` property in projection units is used to determine the zoom level of the tiles.  It is adjusted for `pixelRatio` for historical reasons, it might be best to leave it in case of future changes and do the same for any new resolution.

Differences are noticeable when comparing Maptiler's own MapLibre based example beside the ol-mapbox-style example:

Near the equator ol-mapbox-style's hillshading appears more intense

![image](https://user-images.githubusercontent.com/49240900/230744826-84efcb3d-0830-4c4a-923e-431ce72adbd4.png)

While near 60°N it is less intense than MapLibre

![image](https://user-images.githubusercontent.com/49240900/230744885-7e68470b-2549-4aaa-8c61-ec64ec2918d0.png)

**Comment by mike-000** [comment] 2023-04-21 16:52
There is also a noticeable difference between Mapbox and ol-mapbox-style at any latitude when zoomed out, e.g. the Andes in https://codesandbox.io/s/side-by-side-forked-02zr90?file=/main.js

**Comment by ahocevar** [comment] 2024-03-29 09:14
Duplicate of #777

**Closed by ahocevar** 2024-03-29 09:14 UTC
