### ISSUE TITLE
Only polygon get highlighted, but not line string, or point

### ISSUE THREAD

**Issue by hoogw** [openlayers/ol-mapbox-style#547] opened 2022-05-07 00:49 UTC
If you mouse over park polygon, polygon get highlighted. 
But if you mouse over yellow bike line, no highlight. 

My source code is correct, from console, you can see, "multilinestring" does get selected, but "stroke" line style failed to apply.
 

[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=BikeTrailPark+%28+VectorTileServer+%29+&center_lat=33.66404043711541&center_long=-116.27756582399788&center_zoom=14.724057516788916&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FBikeTrailPark%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=BikeTrailPark+%28+VectorTileServer+%29+&center_lat=33.66404043711541&center_long=-116.27756582399788&center_zoom=14.724057516788916&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FBikeTrailPark%2FVectorTileServer)

![Screen Shot 2022-05-06 at 5 37 38 PM](https://user-images.githubusercontent.com/419582/167230996-5b6a398d-eca1-4c95-a511-fba42b764c56.png)

Here is another example, same problem. only polygon get highlight, line are not.  
I have not test point, 
[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.66339979351223&center_long=-116.30999999999999&center_zoom=17&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.66339979351223&center_long=-116.30999999999999&center_zoom=17&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer)

![Screen Shot 2022-05-06 at 5 45 54 PM](https://user-images.githubusercontent.com/419582/167231260-5d1c76b7-76c2-48d9-ae9d-558c6101e095.png)

**Comment by ahocevar** [comment] 2022-05-07 10:36
You'll have to provide more information (the code you use for highlighting, in its context) and an example where we can reproduce the problem. Both links you provided only show a base map and load with errors.

**Comment by hoogw** [comment] 2022-05-07 14:49
[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.66253765673004&center_long=-116.28215565839609&center_zoom=15.166575251974567&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=ParcelZoning+%28+VectorTileServer+%29+&center_lat=33.66253765673004&center_long=-116.28215565839609&center_zoom=15.166575251974567&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FParcelZoning%2FVectorTileServer)


[https://transparentgov.net/ol2/dist/arcgisvector.html?layer=BikeTrailPark+%28+VectorTileServer+%29+&center_lat=33.6644430909808&center_long=-116.29370277236718&center_zoom=14.724057516788916&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FBikeTrailPark%2FVectorTileServer](https://transparentgov.net/ol2/dist/arcgisvector.html?layer=BikeTrailPark+%28+VectorTileServer+%29+&center_lat=33.6644430909808&center_long=-116.29370277236718&center_zoom=14.724057516788916&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FHosted%2FBikeTrailPark%2FVectorTileServer)

2 example link, works fine, loading takes a while, if you are in other side of earth. 
or try this, click the open layer 

[https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices&org=La+Quinta+CA&_center_lat=33.6634&_center_long=-116.31&_center_zoom=17&select_folder=37&select_layer=-1](https://transparentgov.net/json2tree/esri/server/folder.html?url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices&org=La+Quinta+CA&_center_lat=33.6634&_center_long=-116.31&_center_zoom=17&select_folder=37&select_layer=-1)



The source code have 2 js file, default.js and helper.js

[https://github.com/hoogw/ol2/tree/master/js/arcgis/arcgisvector](https://github.com/hoogw/ol2/tree/master/js/arcgis/arcgisvector)


The highlight code, I learn it from
[https://openlayers.org/en/latest/examples/vector-tile-selection.html](https://openlayers.org/en/latest/examples/vector-tile-selection.html)


![Screen Shot 2022-05-07 at 7 34 42 AM](https://user-images.githubusercontent.com/419582/167258902-08ab789f-9222-46dc-9b62-5a766f325140.png)

**Comment by ahocevar** [comment] 2022-05-07 17:40
Maybe your just not hitting the line. To increase the chance of hitting the line, you can configure the `getFeaturesAtPixels` function with a `hitTolerance` option.

**Comment by hoogw** [comment] 2022-05-07 19:38
I seems hiting the line, I can get the line properties correctly, see screen. 

When hit the line, popup window showing correct line properties. But not highlighted as polygon does. 

Maybe is this problem?  feature type in open layer feature object named "LineString", while in mapbo-layer, type named as 'line', could this name difference cause openlayer not recoganize the line?  

<img width="1297" alt="Screen Shot 2022-05-07 at 12 28 41 PM" src="https://user-images.githubusercontent.com/419582/167269129-13c3a646-a228-4fb4-babd-811967a43861.png">

**Comment by hoogw** [comment] 2022-05-07 20:39
Yes, based on your advise, I figure out where is the problem. 
The problem is my code,    

example is here
[https://openlayers.org/en/latest/examples/hitdetect-vector.html](https://openlayers.org/en/latest/examples/hitdetect-vector.html)

map.getFeaturesAtPixel have bugs, do not use this, instead, use alternative method as above sample shows. 

          Wrong: 
              var features = map.getFeaturesAtPixel(event.pixel, _options_for_getFeaturesAtPixel );

          correct:
                   vtLayer.getFeatures(event.pixel).then(function (features) {...})

**Comment by ahocevar** [comment] 2022-05-07 21:46
In https://github.com/openlayers/ol-mapbox-style/issues/547#issuecomment-1120273812 you mentioned that the popup is correct, but the line is not highlighted. Like you suspect there, it is likely a problem with your style. There is no issue with `map.getFeaturesAtPixel()`.

Can we close this?

**Comment by hoogw** [comment] 2022-05-08 04:01
![Screen Shot 2022-05-07 at 9 00 03 PM](https://user-images.githubusercontent.com/419582/167281161-5c258e7c-2eb0-4a45-81b9-c0568e792db3.png)

I set hitTolerance as 50, (default is 0) still same problem.   Line not highlighted, only polygon highlighted.

**Comment by hoogw** [comment] 2022-05-08 04:09
![Screen Shot 2022-05-07 at 9 05 28 PM](https://user-images.githubusercontent.com/419582/167281260-0612a21a-5218-4e48-a779-af3ea9a62d10.png)

The problem seem here,  like my previous screen shot. 
why polygon get pickup, because, in openlayer feature object and mapbox-object, polygon type always "polygon"

why line failed, because, in openlayer feature object, type name is "LineString", in mapbox-object, type name is 'line', somewhere, type is "MultiLineString",  type name is inconsist, cause failed to highlight line.

**Comment by hoogw** [comment] 2022-05-08 04:22
<img width="1434" alt="Screen Shot 2022-05-07 at 9 22 14 PM" src="https://user-images.githubusercontent.com/419582/167281625-4462c902-4ffc-43a2-9a7d-5e00f0a8e9b6.png">

style seem ok, no problem.

**Comment by hoogw** [comment] 2022-05-08 05:39
<img width="1396" alt="Screen Shot 2022-05-07 at 10 30 18 PM" src="https://user-images.githubusercontent.com/419582/167283242-aa6c8817-ad00-421d-8145-6dcf46b791ae.png">

I still fill the problem is inside your library. 
See this picture, if it is polygon, a feature with "ol_uid" was correctly showing. 

If it is line,  none of feature have "ol_uid". which is not correct. at least should have 1 feature have "ol_uid"

Which library generate "ol_uid"? openlayers ? or this ol-mapbox-style?
I think it is ol-mapbox-style generate "ol_uid". 

The problem is when you generate "ol_uid", if it is polygon,  the type name match, always use "polygon", good.
if it line, problem occur, because type name mismatch.  "MultiLineString", "LineString" was used in openlayer side, 
"line" was used in ol-mapbox-style side,  this mismatch maybe cause previous missing of  "ol_uid"

**Comment by hoogw** [comment] 2022-05-08 07:00
<img width="1103" alt="Screen Shot 2022-05-07 at 11 57 02 PM" src="https://user-images.githubusercontent.com/419582/167285458-957ef482-2a6b-4840-b34d-38ca9a2c641c.png">

my line style is correct. If I show all line, point, polygon style without filter to selected feature, it looks like above, 

Below I comment out 2 line of if, for doing so. 
![Screen Shot 2022-05-07 at 11 58 58 PM](https://user-images.githubusercontent.com/419582/167285513-8e28a2d2-1b0e-4a41-ab17-bea8205916a7.png)

**Comment by ahocevar** [comment] 2022-05-08 11:09
Don't use `ol_uid` for selection. You need to use the feature's id, because the goal is to select all line segments from all tiles where the feature id matches. Otherwise only the part of the line that was actually clicked will be drawn with the select style. Obviously this only works if your lines have feature ids. If they don't, you need to generate the tiles in a way that the features do have feature ids.

**Comment by hoogw** [comment] 2022-05-08 15:13
![Screen Shot 2022-05-08 at 8 10 47 AM](https://user-images.githubusercontent.com/419582/167302805-0cfa91c0-4dab-485c-9652-9478cd6b4cf2.png)

all the `id_`  feature id, feature,getId() is undefined.  see picture. 
why is that?  I have to use `ol_uid`

**Comment by ahocevar** [comment] 2022-05-08 16:41
This is a problem with your data. When creating tiles, you need to make sure each feature has an integer `id`. If you don't have that, you need an attribute in each feature to uniquely identify it. You can configure the `MVT` format with an `idProperty` to use that property as id.

**Comment by hoogw** [comment] 2022-05-08 20:52
I have no control of feature id.  all the vector tile is automatically create by arcgis server and arc pro.  The data is as is, no way to hack arc pro to add feature id.
At least, the polyon is working fine, you can highlight polygon. Seem the way as is at least get polyon working.

**Closed** 2022-05-09 05:22 UTC
