### ISSUE TITLE
Undesired tile boundaries while displaying MVT

### ISSUE THREAD

**Issue by MSPKarengeo** [openlayers/ol-mapbox-style#784] opened 2023-01-10 14:11 UTC
Hi everyone, 
I'm having the same problem to this issue: https://github.com/openlayers/openlayers/issues/10348. 
The MVT has some portions of tile boundaries inside the vector tile. I tried to modify the buffer of tile like to cover the area that the line seems to lose information, but no changes. 
![image](https://user-images.githubusercontent.com/90481471/211573605-92f36eb5-f3f3-4706-b983-7df9913e2483.png)

Do you have any idea to resolve this problem?

**Comment by ahocevar** [comment] 2023-01-10 14:16
@MSPKarengeo Can you share the two tiles from the above screenshot?

**Comment by MSPKarengeo** [comment] 2023-01-10 15:56
thank you for your answer. Here you have the vector tile who has problems: 
https://vectortiles-vigilance.alpha.geomatique.ninja/maps/dev/cluster_k/{z}/{x}/{y}.pbf 
Let me know if you have problems to get in. 
Thanks!

**Comment by ahocevar** [comment] 2023-01-10 17:17
Please also provide the z, y, and y of the tiles in your screenshot.

**Comment by ahocevar** [comment] 2023-01-10 18:06
It looks like your case is different from https://github.com/openlayers/openlayers/issues/10348, because you're rendering a point, not a polygon. Can you also provide the style you're using?

**Comment by MSPKarengeo** [comment] 2023-01-10 18:30
Thank you for your time and for the precision. Yes, we are working whit a point and the size of him changes in each zoom level. Here the link: https://d2hxgj5dyem7b0.cloudfront.net/assets/style/cluster_k.json
You can see in different zoom levels 6, 7 and 8 the lines of the tile boundaries are there. 
zoom level 6 
![image](https://user-images.githubusercontent.com/90481471/211632713-90a56845-438f-4217-8f88-b1282fe18da2.png)

zoom level 7 
![image](https://user-images.githubusercontent.com/90481471/211633206-4bf2ded1-ed96-41a1-8899-5e6ac6e94188.png)

**Comment by ahocevar** [comment] 2023-01-10 20:10
@MSPKarengeo Unfortunately I cannot reproduce the problem locally. Can you provide a link to a complete working example that shows the issue. Also, which browser, and operating system are you using? What is the output of `window.devicePixelRatio` on the browser's JavaScript console?

**Comment by MSPKarengeo** [comment] 2023-01-11 16:01
Hi Andreas, thank you for your answer: 
Here you have the link of complete job https://d2hxgj5dyem7b0.cloudfront.net/carte. Actually, I’m working on Windows 10 Entreprise with chrome 108.0.5359.125 and my colleagues have Ubuntu 22.10 et Chromium 108.0.5359.124. and our window.devicePixelRatio is 1.

**Comment by MSPKarengeo** [comment] 2023-01-11 16:46
Those are the location, that you ask before: 
https://vectortiles-vigilance.alpha.geomatique.ninja/maps/dev/cluster_k/6/19/22.pbf
https://vectortiles-vigilance.alpha.geomatique.ninja/maps/dev/cluster_k/6/20/22.pbf

**Comment by MSPKarengeo** [comment] 2023-01-11 21:18
Thank you very much again for the time agreed to this problem. I understand that the problem is not related to 10348. 
I'm going to share your idea about scale css transform with my colleagues and see if we can find something.
Greetings

**Comment by ahocevar** [comment] 2023-02-28 19:33
Can we close this issue?

**Comment by MSPKarengeo** [comment] 2023-02-28 20:53
yes sure. thanks

**Closed** 2023-02-28 20:54 UTC
